name: Scores by Soren
favicon: null
layout_spectrum: 0.8395938186440617
typography_spectrum: 0.7718557235784829
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6970493861008435
  lightness: 0.7848282167688012
  saturation: 0.5063999767880887
  rhythmicContrast: 0.4895096276886761
purpose: []
